const getJSON=async(path)=>{const r=await fetch(path);if(!r.ok)throw new Error(`تعذر تحميل ${path}`);return r.json()};const q=s=>document.querySelector(s);
function lessonCard(l){return `<article class="card lesson-card"><div class="lesson-num">${l.id}</div><span class="badge">الصفحات ${l.startPage}-${l.endPage}</span><h3>${l.title}</h3><p>${l.hours} ساعة تدريبية</p><div class="spacer"></div><a class="btn primary" href="./lesson.html?id=${l.id}">فتح الدرس</a></article>`}
function tableHTML(t){return `<article class="card" id="${t.id}"><div class="card-head"><h2>${t.title}</h2><a class="btn small" href="./assets/docs/SP128.pdf#page=${t.sourcePage}" target="_blank">المصدر: صفحة ${t.sourcePage}</a></div><div class="table-wrap"><table><thead><tr>${t.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></article>`}
async function initHome(){const el=q('#lesson-grid');if(!el)return;const ls=await getJSON('./data/lessons.json');el.innerHTML=ls.map(lessonCard).join('')}
async function initLessons(){const el=q('#lessons-full-grid');if(!el)return;const ls=await getJSON('./data/lessons.json');el.innerHTML=ls.map(lessonCard).join('')}
async function initCourse(){if(!q('#course-stats'))return;const [course,pages,tables]=await Promise.all([getJSON('./data/course.json'),getJSON('./data/pages.json'),getJSON('./data/tables.json')]);q('#course-stats').innerHTML=[['عدد الدروس',course.lessons.length],['إجمالي الساعات',course.totalHours],['عدد صفحات المصدر',course.pages],['الكود',course.code]].map(([a,b])=>`<article class="card stat-card"><span>${a}</span><strong>${b}</strong></article>`).join('');q('#program-page-text').textContent=pages.find(p=>p.page===5)?.text||'';q('#hours-table').innerHTML=tableHTML(tables.find(t=>t.id==='hours'))}
async function initTables(){const el=q('#tables-container');if(!el)return;const tables=await getJSON('./data/tables.json');el.innerHTML=tables.map(tableHTML).join('')}
async function initLesson(){if(!q('#lesson-title'))return;const params=new URLSearchParams(location.search);const id=Number(params.get('id')||1);const [ls,pages,figs]=await Promise.all([getJSON('./data/lessons.json'),getJSON('./data/pages.json'),getJSON('./data/figures.json')]);const lesson=ls.find(x=>x.id===id)||ls[0];const lessonPages=pages.filter(p=>p.page>=lesson.startPage&&p.page<=lesson.endPage);q('#lesson-title').textContent=lesson.title;q('#lesson-side-title').textContent=`الدرس ${lesson.id}`;q('#lesson-range').textContent=`الصفحات ${lesson.startPage}-${lesson.endPage} · ${lesson.hours} ساعات`;const sel=q('#page-select');sel.innerHTML=lessonPages.map(p=>`<option value="${p.page}">صفحة ${p.page}</option>`).join('');const buttons=q('#page-buttons');buttons.innerHTML=lessonPages.map(p=>`<button type="button" data-page="${p.page}">${p.page}</button>`).join('');
function showPage(n){const p=lessonPages.find(x=>x.page===Number(n))||lessonPages[0];sel.value=p.page;q('#page-text').textContent=p.text||'لا يوجد نص مستخرج في هذه الصفحة. راجعي الصفحة الأصلية.';q('#page-title').textContent=`النص المستخرج - صفحة ${p.page}`;q('#page-badge').textContent=`صفحة ${p.page}`;q('#pdf-frame').src=`./assets/docs/SP128.pdf#page=${p.page}&view=FitH`;q('#open-source').href=`./assets/docs/SP128.pdf#page=${p.page}`;buttons.querySelectorAll('button').forEach(b=>b.classList.toggle('active',Number(b.dataset.page)===p.page));const f=figs.find(x=>x.page===p.page);q('#page-figures').innerHTML=f?.images?.length?f.images.map((src,i)=>`<figure class="figure-card"><img loading="lazy" src="${src}" alt="صورة أصلية مستخرجة من الصفحة ${p.page}"><div class="body"><strong>صفحة ${p.page}</strong><p>${f.captions?.[i]||f.captions?.[0]||'صورة من المصدر الأصلي'}</p></div></figure>`).join(''):'<p class="muted">لا توجد صورة مستقلة مستخرجة لهذه الصفحة؛ يمكن مشاهدة الصفحة الأصلية أعلاه.</p>';history.replaceState(null,'',`?id=${lesson.id}&page=${p.page}`)}
showPage(Number(params.get('page')||lesson.startPage));sel.addEventListener('change',()=>showPage(sel.value));buttons.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)});q('#toggle-source').addEventListener('click',()=>q('#source-panel').classList.toggle('hidden'))}
async function initGallery(){const grid=q('#gallery-grid');if(!grid)return;const [figs,lessons]=await Promise.all([getJSON('./data/figures.json'),getJSON('./data/lessons.json')]);const filter=q('#gallery-filter'),lessonSel=q('#gallery-lesson');lessonSel.innerHTML+=lessons.map(l=>`<option value="${l.id}">الدرس ${l.id}</option>`).join('');function render(){const term=filter.value.trim(),lid=lessonSel.value,items=[];figs.filter(f=>(!lid||String(f.lessonId)===lid)&&(!term||String(f.page).includes(term)||(f.captions||[]).join(' ').includes(term))).forEach(f=>f.images.forEach((src,i)=>items.push(`<figure class="figure-card"><a href="${src}" target="_blank"><img loading="lazy" src="${src}" alt="صورة أصلية من صفحة ${f.page}"></a><div class="body"><span class="badge">صفحة ${f.page}</span><p>${f.captions?.[i]||f.captions?.[0]||'صورة أصلية من ملف PDF'}</p><a class="btn small" href="./assets/docs/SP128.pdf#page=${f.page}" target="_blank">الصفحة الأصلية</a></div></figure>`)));grid.innerHTML=items.join('')||'<p>لا توجد نتائج.</p>'}filter.addEventListener('input',render);lessonSel.addEventListener('change',render);render()}
Promise.allSettled([initHome(),initLessons(),initCourse(),initTables(),initLesson(),initGallery()]);